---
 - name: Create mount points and mount ANF volumes on site 1
   hosts: hn1-site1
   become: yes

   vars:
      sid: HN1
      sapuser: hn1adm
      anfpairs:
        - src: 10.4.3.4:/sap-hn1-c1-data1
          path: /hana/data/{{ sid }}/mnt00001
        - src: 10.4.3.4:/sap-hn1-c1-data2
          path: /hana/data/{{ sid }}/mnt00002
        - src: 10.4.3.4:/sap-hn1-c1-log1
          path: /hana/log/{{ sid }}/mnt00001
        - src: 10.4.3.4:/sap-hn1-c1-log2
          path: /hana/log/{{ sid }}/mnt00002
        - src: 10.4.3.5:/sap-hn1-c1-shared
          path: /hana/shared/{{ sid }}

   tasks:
     - name: Create directories with permissions
       ansible.builtin.file:
         path: "{{ item.path }}"
         state: directory
         owner: "{{ sapuser }}"
         group: 'sapsys'
         mode: '0755'
       loop: "{{ anfpairs }}"

     - name: Mount the filesystems
       ansible.posix.mount:
         path: "{{ item.path }}"
         src: "{{ item.src }}"
         fstype: nfs
         opts: rw,hard,rsize=1048576,wsize=1048576,sec=sys,vers=4.1,nofail
         state: mounted
       loop: "{{ anfpairs }}"

     - name: Set permissions once more
       ansible.builtin.file:
         path: "{{ item.path }}"
         state: directory
         owner: "{{ sapuser }}"
         group: 'sapsys'
         mode: '0755'
       loop: "{{ anfpairs }}"

 - name: Create mount points and mount ANF volumes on site 2
   hosts: hn1-site2
   become: yes

   vars:
      sid: HN1
      sapuser: hn1adm
      anfpairs:
        - src: 10.4.3.4:/sap-hn1-c2-data1
          path: /hana/data/{{ sid }}/mnt00001
        - src: 10.4.3.4:/sap-hn1-c2-data2
          path: /hana/data/{{ sid }}/mnt00002
        - src: 10.4.3.4:/sap-hn1-c2-log1
          path: /hana/log/{{ sid }}/mnt00001
        - src: 10.4.3.4:/sap-hn1-c2-log2
          path: /hana/log/{{ sid }}/mnt00002
        - src: 10.4.3.4:/sap-hn1-c2-shared
          path: /hana/shared/{{ sid }}

   tasks:
     - name: Create directories with permissions
       ansible.builtin.file:
         path: "{{ item.path }}"
         state: directory
         owner: "{{ sapuser }}"
         group: 'sapsys'
         mode: '0755'
       loop: "{{ anfpairs }}"

     - name: Mount the filesystems
       ansible.posix.mount:
         path: "{{ item.path }}"
         src: "{{ item.src }}"
         fstype: nfs
         opts: rw,hard,rsize=1048576,wsize=1048576,sec=sys,vers=4.1,nofail
         state: mounted
       loop: "{{ anfpairs }}"

     - name: Set permissions once more
       ansible.builtin.file:
         path: "{{ item.path }}"
         state: directory
         owner: "{{ sapuser }}"
         group: 'sapsys'
         mode: '0755'
       loop: "{{ anfpairs }}"
