---
 - name: OS fixes
   hosts: hn1-all
   become: yes

   vars:
      sid: HN1
      sapuser: hn1adm

   tasks:
     - name: Add default tasks
       ansible.builtin.lineinfile:
         path: /etc/systemd/system.conf
         regexp: '^DefaultTasksMax='
         line: DefaultTasksMax=4096

     - name: Restart daemon
       ansible.builtin.command:
         cmd: systemctl daemon-reload

     - name: Add default tasks
       ansible.builtin.lineinfile:
         path: /etc/sysctl.conf
         regexp: '^vm.dirty_bytes'
         line: vm.dirty_bytes = 629145600

     - name: Add default tasks
       ansible.builtin.lineinfile:
         path: /etc/sysctl.conf
         regexp: '^vm.dirty_background_bytes'
         line: vm.dirty_background_bytes = 314572800

     - name: Fix cloud netconfig
       ansible.builtin.lineinfile:
         path: /etc/sysconfig/network/ifcfg-eth0
         regexp: '^CLOUD_NETCONFIG_MANAGE='
         line: CLOUD_NETCONFIG_MANAGE='no'
