---
- name: Saptune
  hosts: hn1-sap
  become: yes

  vars:
    sid: HN1
    sapuser: hn1adm

  tasks:
  - name: saptune apply
    ansible.builtin.command:
      cmd: saptune solution apply HANA

  - name: saptune start
    ansible.builtin.command:
      cmd: saptune daemon start
