---
 - name: Partition, format and mount /usr/sap
   hosts: hn1-sap
   become: yes

   vars:
      sid: HN1

   tasks:
#    - name: Create a new LVM primary partition
#      community.general.parted:
#        device: /dev/disk/azure/scsi1/lun0
#        number: 1
#        state: present
#        flags: [ lvm ]

     - name: Create a volume group
       community.general.lvg:
         vg: HN1usrsap
         pvs: /dev/disk/azure/scsi1/lun0-part1

#     - name: Create a logical volume the size of all remaining space in the volume group
#       community.general.lvol:
#         vg: HN1usrsap
#         lv: lvHN1usrsap
#         size: 100%FREE     

     - name: Create an xfs filesystem
       community.general.filesystem:
         fstype: xfs
         dev: /dev/HN1usrsap/lvHN1usrsap

     - name: Mount the filesystem
       ansible.posix.mount:
         path: /usr/sap/HN1
         src: /dev/HN1usrsap/lvHN1usrsap
         fstype: xfs
         opts: defaults,nofail
         state: mounted